export interface Verse {
  num: string
  ko: string
  en: string
  traditions: string[]
  traditions_en: string[]
  reflection_ko: string
  reflection_en: string
}

export interface Chapter {
  id: number
  title_ko: string
  title_en: string
  intro_ko: string
  intro_en: string
  theme: string
  verses: Verse[]
}

export const scriptureVerses: { chapters: Chapter[] } = {
  chapters: [
    {
      id: 1,
      title_ko: '깨어남의 길',
      title_en: 'The Path of Awakening',
      intro_ko: '깨어남은 어딘가에 도착하는 게 아니에요.\n이미 여기 있는 것을, 다시 보는 거예요.',
      intro_en: 'Awakening is not arriving somewhere new.\nIt is seeing what has always been here.',
      theme: 'awakening',
      verses: [
        {
          num: '1:1',
          ko: '눈을 감아보세요. 어둠이 아니라,\n보고 있는 누군가가 느껴질 거예요.\n그게 바로 당신이에요.',
          en: 'Close your eyes. It is not darkness you find.\nYou find someone watching — and that someone is you.',
          traditions: ['불교', '베단타'],
          traditions_en: ['Buddhism', 'Vedanta'],
          reflection_ko: '눈을 감으면, 거기서 무엇을 만나나요?',
          reflection_en: 'When you close your eyes, who is it that you meet?',
        },
        {
          num: '1:2',
          ko: '그 보는 자를 찾았다면, 생각을 멈추려 애쓰지 마세요.\n강물을 막으면 넘치듯이.\n그냥 바라보세요. 생각은 지켜볼 때 스스로 고요해져요.',
          en: 'Now that you have found the watcher, do not try to silence your thoughts.\nA dammed river only overflows.\nJust watch. Thoughts grow quiet on their own when you stop fighting them.',
          traditions: ['선불교', '도교'],
          traditions_en: ['Zen', 'Taoism'],
          reflection_ko: '지금 떠오르는 생각을, 싸우지 않고 바라볼 수 있나요?',
          reflection_en: 'Can you watch the thoughts arising right now without fighting them?',
        },
        {
          num: '1:3',
          ko: '바라보는 법을 알았다면, 이제 멀리 갈 필요 없어요.\n오늘 아침 마신 물 한 잔, 거기에 깨어남이 있어요.',
          en: 'Once you learn to watch, you need not go far.\nThis morning\'s glass of water — awakening is already there.',
          traditions: ['선불교', '수피즘'],
          traditions_en: ['Zen', 'Sufism'],
          reflection_ko: '가장 평범한 순간에서, 무엇을 발견할 수 있을까요?',
          reflection_en: 'What can you discover in the most ordinary moment today?',
        },
        {
          num: '1:4',
          ko: '물 한 잔에서도 깨어남을 느꼈다면, 이제 더 깊이 들어가 보세요.\n세상이 시끄러울수록, 내 안은 더 고요해져야 해요.\n깊은 바다는 수면의 폭풍을 몰라요.',
          en: 'If you found awakening in a glass of water, now go deeper.\nThe louder the world, the stiller you must become.\nThe deep ocean knows nothing of the storm above.',
          traditions: ['스토아', '도교'],
          traditions_en: ['Stoicism', 'Taoism'],
          reflection_ko: '지금 내 안은 얼마나 깊은 곳에 있나요?',
          reflection_en: 'How deep within yourself can you reach right now?',
        },
        {
          num: '1:5',
          ko: '그 깊은 곳에서 진짜 나를 찾겠다고 결심하는 순간,\n깨어남은 이미 시작된 거예요.\n찾으려는 마음 자체가 첫 번째 빛이에요.',
          en: 'The moment you resolve to find your true self in that depth,\nawakening has already begun.\nThe desire to seek is itself the first light.',
          traditions: ['기독교 신비주의', '불교'],
          traditions_en: ['Christian Mysticism', 'Buddhism'],
          reflection_ko: '나를 찾으려는 그 마음은, 어디에서 왔을까요?',
          reflection_en: 'Where does this desire to seek yourself come from?',
        },
        {
          num: '1:6',
          ko: '하지만 찾겠다는 빛만으로는 부족해요.\n아는 것과 사는 것 사이에는 간격이 있어요.\n그 간격을 줄여가는 것, 그게 수행이에요.',
          en: 'But the light of seeking alone is not enough.\nThere is a gap between knowing and living.\nClosing that gap, step by step — that is practice.',
          traditions: ['유교', '스토아'],
          traditions_en: ['Confucianism', 'Stoicism'],
          reflection_ko: '알면서도 살지 못하고 있는 것은 무엇인가요?',
          reflection_en: 'What do you know to be true, yet fail to live by?',
        },
        {
          num: '1:7',
          ko: '앎과 삶 사이의 그 간격을 어떻게 줄이냐고요?\n모든 전통이 같은 말을 해요.\n"멈춰봐. 그러면 보일 거야."',
          en: 'How do you close that gap?\nEvery tradition says the same thing:\n"Be still. Then you will see."',
          traditions: ['범전통'],
          traditions_en: ['Universal'],
          reflection_ko: '오늘 5분만 멈춰본다면, 무엇이 보일까요?',
          reflection_en: 'If you pause for just five minutes today, what might you see?',
        },
      ],
    },
    {
      id: 2,
      title_ko: '고통과 치유',
      title_en: 'Suffering and Healing',
      intro_ko: '누구나 아파요.\n하지만 아픔을 끝까지 통과한 사람은, 전에 없던 빛을 품게 돼요.',
      intro_en: 'Everyone hurts.\nBut those who walk all the way through their pain carry a light they never had before.',
      theme: 'suffering',
      verses: [
        {
          num: '2:1',
          ko: '고통은 벌이 아니에요.\n고통은 질문이에요. "지금, 나에게 정말 중요한 건 뭘까?"',
          en: 'Suffering is not punishment.\nIt is a question: "What truly matters to me right now?"',
          traditions: ['불교', '기독교'],
          traditions_en: ['Buddhism', 'Christianity'],
          reflection_ko: '지금 내 고통이 묻고 있는 질문은 무엇인가요?',
          reflection_en: 'What question is your pain asking you right now?',
        },
        {
          num: '2:2',
          ko: '그 질문 앞에서 우리는 부러져요.\n하지만 부러진 뼈가 더 단단해지듯, 부러진 마음도 더 넓어질 수 있어요.',
          en: 'That question can break us.\nBut as a broken bone grows back stronger, a broken heart can grow back wider.',
          traditions: ['수피즘', '스토아'],
          traditions_en: ['Sufism', 'Stoicism'],
          reflection_ko: '내가 부러진 곳은 어디이고, 거기서 어떤 빛이 들어오나요?',
          reflection_en: 'Where have you been broken, and what light is entering there?',
        },
        {
          num: '2:3',
          ko: '넓어지려면 먼저 질문을 바꿔야 해요.\n"왜 하필 나에게?"가 아니라, "이게 나에게 뭘 가르치고 있지?"라고요.',
          en: 'To grow wider, first change the question.\nNot "Why me?" but "What is this teaching me?"',
          traditions: ['스토아', '이슬람'],
          traditions_en: ['Stoicism', 'Islam'],
          reflection_ko: '최근 어려움이 내게 가르쳐준 게 있다면 뭘까요?',
          reflection_en: 'What has a recent difficulty taught you?',
        },
        {
          num: '2:4',
          ko: '배움이 시작되면, 눈물이 나올 수 있어요.\n그건 약한 게 아니에요. 얼어붙은 땅이 녹을 때 물이 흐르는 거예요.',
          en: 'When the learning begins, tears may come.\nThat is not weakness. When frozen ground thaws, water flows.',
          traditions: ['기독교', '도교'],
          traditions_en: ['Christianity', 'Taoism'],
          reflection_ko: '마지막으로 눈물을 흘린 건 언제예요? 그때 무엇이 녹았나요?',
          reflection_en: 'When did you last let yourself cry? What thawed inside you?',
        },
        {
          num: '2:5',
          ko: '눈물이 마르면 치유가 시작돼요.\n치유는 잊는 게 아니에요. 기억하면서도 평화로울 수 있다는 걸 배우는 거예요.',
          en: 'When the tears dry, healing begins.\nHealing is not forgetting. It is learning to remember in peace.',
          traditions: ['불교', '현대 심리학'],
          traditions_en: ['Buddhism', 'Modern Psychology'],
          reflection_ko: '기억하면서도 고요할 수 있는 상처가 있나요?',
          reflection_en: 'Is there a wound you can remember and still feel at peace?',
        },
        {
          num: '2:6',
          ko: '평화롭게 기억할 수 있게 되면, 그 상처는 문이 돼요.\n내 아픔을 통과한 만큼, 다른 사람의 아픔에 닿을 수 있으니까요.',
          en: 'Once you can remember in peace, the wound becomes a door.\nThe deeper you have hurt, the deeper you can reach into another\'s pain.',
          traditions: ['기독교', '불교'],
          traditions_en: ['Christianity', 'Buddhism'],
          reflection_ko: '내 아픔이 누군가에게 위로가 된 적이 있나요?',
          reflection_en: 'Has your pain ever become comfort for someone else?',
        },
        {
          num: '2:7',
          ko: '다른 사람의 아픔에 닿으려면, 먼저 내 아픔을 피하지 않아야 해요.\n고통을 피하면 커지지만, 안아주면 달라져요.',
          en: 'To reach another\'s pain, you must first stop running from your own.\nRun from pain and it grows. Hold it gently, and it transforms.',
          traditions: ['불교', '수피즘'],
          traditions_en: ['Buddhism', 'Sufism'],
          reflection_ko: '지금 피하고 있는 고통이 있다면, 오늘 살짝 안아줄 수 있을까요?',
          reflection_en: 'Is there a pain you are avoiding? Could you gently hold it today?',
        },
        {
          num: '2:8',
          ko: '안아주고 나면, 밤이 조금씩 걷혀요.\n가장 깊은 밤 뒤에 새벽이 오듯, 가장 깊은 고통 뒤에 이해가 찾아와요.',
          en: 'Once you hold it, the night begins to lift.\nAs dawn follows the deepest dark, understanding follows the deepest pain.',
          traditions: ['이슬람', '기독교', '도교'],
          traditions_en: ['Islam', 'Christianity', 'Taoism'],
          reflection_ko: '가장 힘들었던 시간이 결국 내게 준 선물은 뭐였나요?',
          reflection_en: 'What gift did your hardest season eventually bring you?',
        },
      ],
    },
    {
      id: 3,
      title_ko: '사랑과 연결',
      title_en: 'Love and Connection',
      intro_ko: '사랑은 이해하는 게 아니에요.\n사랑은 그 안으로 들어가는 거예요.',
      intro_en: 'Love is not something you understand.\nIt is something you enter.',
      theme: 'love',
      verses: [
        {
          num: '3:1',
          ko: '사랑한다는 건, 상대를 고치려는 게 아니에요.\n있는 그대로 바라보는 거예요.\n그 시선 자체가 사랑이에요.',
          en: 'To love is not to fix someone.\nIt is to see them as they are.\nThat gaze itself is love.',
          traditions: ['불교', '기독교'],
          traditions_en: ['Buddhism', 'Christianity'],
          reflection_ko: '내가 사랑하는 사람을, 고치려 하지 않고 바라본 적이 있나요?',
          reflection_en: 'Have you ever looked at someone you love without wanting to change them?',
        },
        {
          num: '3:2',
          ko: '그런데 누군가를 있는 그대로 보려면,\n먼저 나를 있는 그대로 볼 수 있어야 해요.\n자기 안에 뿌리 내리지 못한 사랑은 오래가지 못해요.',
          en: 'But to see someone as they are,\nyou must first see yourself as you are.\nLove that has no roots within you cannot last.',
          traditions: ['베단타', '현대 영성'],
          traditions_en: ['Vedanta', 'Modern Spirituality'],
          reflection_ko: '나 자신을, 있는 그대로 바라보고 있나요?',
          reflection_en: 'Are you seeing yourself as you truly are?',
        },
        {
          num: '3:3',
          ko: '나를 알고 나면, 다른 사람이 보여요.\n같은 생각을 하지 않아도 손을 잡을 수 있어요.\n다름이 벽이 아니라 다리가 돼요.',
          en: 'Once you know yourself, you begin to see others.\nYou can hold hands without thinking alike.\nDifference becomes a bridge, not a wall.',
          traditions: ['유교', '기독교'],
          traditions_en: ['Confucianism', 'Christianity'],
          reflection_ko: '나와 다른 사람의 손을, 오늘 잡아볼 수 있나요?',
          reflection_en: 'Can you reach for the hand of someone different from you today?',
        },
        {
          num: '3:4',
          ko: '다름을 건너려면 자비가 필요해요.\n자비는 위에서 내려다보는 동정이 아니에요.\n"나도 저럴 수 있었어"라는 겸손한 인식이에요.',
          en: 'Crossing difference takes compassion.\nCompassion is not pity looking down.\nIt is the humble recognition: "I could have been there too."',
          traditions: ['불교', '이슬람'],
          traditions_en: ['Buddhism', 'Islam'],
          reflection_ko: '오늘 누군가를 보며 "나도 저럴 수 있었어"라고 느낀 적 있나요?',
          reflection_en: 'Did you look at someone today and feel, "I could have been there too"?',
        },
        {
          num: '3:5',
          ko: '자비로 바라보면, 용서도 가능해져요.\n용서는 상대를 위한 게 아니에요.\n나를 묶고 있는 사슬을 푸는 거예요.',
          en: 'When you see with compassion, forgiveness becomes possible.\nForgiveness is not for them.\nIt is unlocking the chain that binds you.',
          traditions: ['기독교', '스토아'],
          traditions_en: ['Christianity', 'Stoicism'],
          reflection_ko: '아직 용서하지 못한 것이 있다면, 그것이 나를 묶고 있진 않나요?',
          reflection_en: 'If there is something you have not forgiven, is it still binding you?',
        },
        {
          num: '3:6',
          ko: '용서가 시작되면, 판단이 내려가요.\n판단은 귀를 막지만, 열린 마음은 귀를 열어요.\n그때 비로소 상대가 들려요.',
          en: 'When forgiveness begins, judgment falls away.\nJudgment closes the ears, but an open heart opens them.\nOnly then can you truly hear the other.',
          traditions: ['유교', '수피즘'],
          traditions_en: ['Confucianism', 'Sufism'],
          reflection_ko: '누군가에 대한 판단을 내려놓으면, 무엇이 들리나요?',
          reflection_en: 'If you set down your judgment of someone, what do you hear?',
        },
        {
          num: '3:7',
          ko: '판단 없이 듣다 보면, 경계가 흐려져요.\n나와 너 사이의 벽이 사라지면,\n우리가 같은 바다의 파도였다는 걸 알게 돼요.',
          en: 'Listen without judgment, and the boundaries blur.\nWhen the wall between you and me dissolves,\nyou see that we were always waves of the same ocean.',
          traditions: ['베단타', '수피즘', '도교'],
          traditions_en: ['Vedanta', 'Sufism', 'Taoism'],
          reflection_ko: '내 옆의 사람과 나는 어떤 바다를 함께 이루고 있나요?',
          reflection_en: 'What ocean do you and the person beside you share?',
        },
      ],
    },
    {
      id: 4,
      title_ko: '삶과 죽음',
      title_en: 'Life and Death',
      intro_ko: '삶과 죽음은 서로 다른 게 아니에요.\n같은 강물의 물결과 바다예요.',
      intro_en: 'Life and death are not two different things.\nThey are the wave and the ocean of the same water.',
      theme: 'life-death',
      verses: [
        {
          num: '4:1',
          ko: '꽃은 지면서 열매를 준비해요.\n놓아야 할 것을 놓을 때, 새로운 것이 익어가요.',
          en: 'A flower falls to make way for fruit.\nWhen you release what must go, something new ripens.',
          traditions: ['불교', '도교'],
          traditions_en: ['Buddhism', 'Taoism'],
          reflection_ko: '지금 놓아야 할 것은 무엇인가요? 그것이 떠나면 무엇이 익을까요?',
          reflection_en: 'What do you need to release right now? What might ripen once it falls away?',
        },
        {
          num: '4:2',
          ko: '이렇게 무언가 익어가는 동안에도, 매 순간은 작은 탄생이자 작은 죽음이에요.\n들숨과 날숨 사이에, 삶 전체가 들어 있어요.',
          en: 'Even as something ripens, each moment is a small birth and a small death.\nYour whole life fits between one inhale and one exhale.',
          traditions: ['이슬람', '스토아'],
          traditions_en: ['Islam', 'Stoicism'],
          reflection_ko: '지금 이 숨이 마지막이라면, 무엇을 하고 싶나요?',
          reflection_en: 'If this breath were your last, what would you want to be doing right now?',
        },
        {
          num: '4:3',
          ko: '그런데 우리는 이 숨을 당연하게 여기며 미뤄요.\n영원히 살 것처럼 미루고, 내일 죽을 것처럼 두려워해요.\n그 사이에서 오늘이 빠져나가요.',
          en: 'Yet we take this breath for granted and keep postponing.\nWe delay as if we live forever, and fear as if we die tomorrow.\nIn between, today slips away.',
          traditions: ['스토아', '불교'],
          traditions_en: ['Stoicism', 'Buddhism'],
          reflection_ko: '오늘이 빠져나가기 전에, 지금 시작할 수 있는 것은 무엇인가요?',
          reflection_en: 'Before today slips away, what is one thing you could begin right now?',
        },
        {
          num: '4:4',
          ko: '오늘을 놓치지 않겠다고 결심하면, 떠나간 사람들도 다르게 보여요.\n그들은 사라진 게 아니에요. 비가 되어 내리고, 바람이 되어 불어와요.',
          en: 'When you choose not to lose today, even those who have gone look different.\nThey have not vanished. They fall as rain. They blow as wind.',
          traditions: ['불교', '원주민 영성'],
          traditions_en: ['Buddhism', 'Indigenous Spirituality'],
          reflection_ko: '떠나간 사람의 바람이 불어올 때, 어디에서 느끼나요?',
          reflection_en: 'When the wind of someone who has passed blows through, where do you feel it?',
        },
        {
          num: '4:5',
          ko: '그 바람을 느끼려면, 죽음을 바라볼 줄 알아야 해요.\n죽음을 바라보는 건 우울한 게 아니에요.\n삶의 윤곽을 선명하게 해주는 빛이에요.',
          en: 'To feel that wind, you need to learn to face death.\nFacing death is not morbid.\nIt is the light that sharpens the outline of life.',
          traditions: ['스토아', '불교', '기독교'],
          traditions_en: ['Stoicism', 'Buddhism', 'Christianity'],
          reflection_ko: '죽음을 바라볼 때, 지금 이 삶은 어떤 모습으로 보이나요?',
          reflection_en: 'When you look at death, how does this life appear to you?',
        },
        {
          num: '4:6',
          ko: '그 빛 아래에서 보면, 끝은 진짜 끝이 아니에요.\n씨앗은 어둠 속에서 깨져야 싹이 트여요.\n끝이라고 느끼는 바로 그 순간이, 시작이에요.',
          en: 'Under that light, an ending is never truly the end.\nA seed must crack open in darkness to sprout.\nThe very moment that feels like an ending is a beginning.',
          traditions: ['기독교', '수피즘'],
          traditions_en: ['Christianity', 'Sufism'],
          reflection_ko: '지금 끝나고 있는 무언가 속에서, 어떤 시작이 보이나요?',
          reflection_en: 'In something that is ending right now, what beginning can you see?',
        },
        {
          num: '4:7',
          ko: '끝과 시작이 하나라면, 존재 자체가 기적이에요.\n수십억 년의 별먼지가 모여 지금의 당신이 되었어요.',
          en: 'If endings and beginnings are one, then existence itself is a miracle.\nBillions of years of stardust gathered to become you.',
          traditions: ['현대 영성', '힌두교'],
          traditions_en: ['Modern Spirituality', 'Hinduism'],
          reflection_ko: '별먼지였던 내가 지금 여기 있다는 사실이, 오늘은 얼마나 놀라운가요?',
          reflection_en: 'You were once stardust. How miraculous does your existence feel today?',
        },
      ],
    },
    {
      id: 5,
      title_ko: '고요와 수행',
      title_en: 'Stillness and Practice',
      intro_ko: '평화를 알았다면, 이제 그 안에 머무는 법을 배울 차례예요.\n수행은 거창한 것이 아니에요. 매 순간 자기 자신에게 돌아오는 거예요.',
      intro_en: 'If you have glimpsed peace, now it is time to learn to stay there.\nPractice is not grand. It is returning to yourself, moment by moment.',
      theme: 'practice',
      verses: [
        {
          num: '5:1',
          ko: '하루에 5분만 아무것도 하지 않고 앉아 보세요.\n할 일을 멈추는 것, 그것이 가장 깊은 수행의 시작이에요.',
          en: 'Sit for just five minutes a day and do nothing.\nTo stop doing is where the deepest practice begins.',
          traditions: ['선불교', '도교'],
          traditions_en: ['Zen', 'Taoism'],
          reflection_ko: '오늘 5분, 아무것도 하지 않는 시간을 자신에게 줄 수 있나요?',
          reflection_en: 'Can you give yourself five minutes of pure stillness today?',
        },
        {
          num: '5:2',
          ko: '고요히 앉아 있으면 무언가가 들려오기 시작해요.\n기도는 말하는 것이 아니라, 듣는 것이에요.',
          en: 'When you sit in stillness, something begins to speak.\nPrayer is not talking. It is listening.',
          traditions: ['기독교 신비주의', '수피즘'],
          traditions_en: ['Christian Mysticism', 'Sufism'],
          reflection_ko: '말을 멈추고 귀를 기울이면, 무엇이 들리나요?',
          reflection_en: 'If you stop speaking and truly listen, what do you hear?',
        },
        {
          num: '5:3',
          ko: '들리지 않는 날도 있어요. 마음이 흩어지는 날도 있어요.\n그래도 다시 앉는 것, 그것이 수행이에요. 완벽할 필요는 없어요.',
          en: 'Some days you hear nothing. Some days the mind scatters.\nSitting down again anyway — that is the practice. It does not need to be perfect.',
          traditions: ['불교', '스토아'],
          traditions_en: ['Buddhism', 'Stoicism'],
          reflection_ko: '마음이 흩어진 날, 자신을 다그치지 않고 다시 시작할 수 있나요?',
          reflection_en: 'On a scattered day, can you begin again without judging yourself?',
        },
        {
          num: '5:4',
          ko: '다시 앉을 때, 호흡부터 시작해 보세요.\n들이쉴 때 세상을 받아들이고, 내쉴 때 나를 내려놓으세요.',
          en: 'When you sit down again, start with breath.\nBreathe in and receive the world. Breathe out and release yourself.',
          traditions: ['불교', '힌두교'],
          traditions_en: ['Buddhism', 'Hinduism'],
          reflection_ko: '지금 이 자리에서 숨을 한 번 깊이 쉬어 보세요. 무엇이 달라지나요?',
          reflection_en: 'Right where you are, take one deep breath. What shifts?',
        },
        {
          num: '5:5',
          ko: '호흡은 앉아 있을 때만의 것이 아니에요.\n설거지를 하면서도, 길을 걸으면서도 숨을 느낄 수 있어요.\n수행은 특별한 장소에 있지 않아요.',
          en: 'Breath is not only for sitting.\nYou can feel it while washing dishes, while walking down the street.\nPractice lives in no special place.',
          traditions: ['선불교', '이슬람'],
          traditions_en: ['Zen', 'Islam'],
          reflection_ko: '오늘 가장 평범한 순간에 숨을 한 번 느껴볼 수 있나요?',
          reflection_en: 'In the most ordinary moment today, can you pause and feel one breath?',
        },
        {
          num: '5:6',
          ko: '일상의 수행은 몸에서 시작돼요.\n몸은 마음이 사는 집이에요. 집을 돌보지 않으면, 안에 있는 이도 편하지 않아요.',
          en: 'Everyday practice begins with the body.\nThe body is the home where the mind lives. Neglect the house, and the one within suffers.',
          traditions: ['요가', '유교'],
          traditions_en: ['Yoga', 'Confucianism'],
          reflection_ko: '오늘 내 몸에게 작은 돌봄 하나를 선물할 수 있나요?',
          reflection_en: 'What small act of care can you offer your body today?',
        },
        {
          num: '5:7',
          ko: '몸을 돌보았다면, 가끔은 밖으로 나가 보세요.\n나무는 그냥 서 있는 법을 가르쳐주고, 바람은 놓아주는 법을 보여줘요.',
          en: 'Once you have cared for the body, step outside now and then.\nTrees teach how to simply stand; wind shows how to let go.',
          traditions: ['도교', '원주민 영성'],
          traditions_en: ['Taoism', 'Indigenous Spirituality'],
          reflection_ko: '마지막으로 하늘을 올려다보며 가만히 선 건 언제인가요?',
          reflection_en: 'When did you last look up at the sky and simply stand still?',
        },
        {
          num: '5:8',
          ko: '자연이 가르쳐주듯, 수행에는 끝이 없어요.\n끝이 없다는 것이 아름다운 거예요. 매일이 첫날이에요.',
          en: 'As nature teaches, practice has no finish line.\nThat it never ends is what makes it beautiful. Every day is day one.',
          traditions: ['불교', '수피즘', '스토아'],
          traditions_en: ['Buddhism', 'Sufism', 'Stoicism'],
          reflection_ko: '오늘이 수행의 첫날이라면, 무엇부터 해보겠어요?',
          reflection_en: 'If today were the very first day of your practice, what would you do?',
        },
      ],
    },
  ],
}
